/data/chromatix-test /system/lib/libchromatix_imx214_liveshot.so > /sdcard/chromatix_imx214_liveshot.h
/data/chromatix-test /system/lib/libchromatix_imx215_liveshot.so > /sdcard/chromatix_imx215_liveshot.h
/data/chromatix-test /system/lib/libchromatix_imx135_liveshot.so > /sdcard/chromatix_imx135_liveshot.h
/data/chromatix-test /system/lib/libchromatix_imx219_liveshot.so > /sdcard/chromatix_imx219_liveshot.h
/data/chromatix-test /system/lib/libchromatix_imx224_liveshot.so > /sdcard/chromatix_imx224_liveshot.h
/data/chromatix-test /system/lib/libchromatix_imx225_liveshot.so > /sdcard/chromatix_imx225_liveshot.h
/data/chromatix-test /system/lib/libchromatix_imx226_liveshot.so > /sdcard/chromatix_imx226_liveshot.h
/data/chromatix-test /system/lib/libchromatix_s5k3m2_liveshot.so > /sdcard/chromatix_s5k3m2_liveshot.h
/data/chromatix-test /system/vendor/lib/libchromatix_SKUAA_ST_gc0339_common.so > /sdcard/chromatix_SKUAA_ST_gc0339_common.h
/data/chromatix-test /system/vendor/lib/libchromatix_SKUAA_ST_gc0339_default_video.so > /sdcard/chromatix_SKUAA_ST_gc0339_default_video.h
/data/chromatix-test /system/vendor/lib/libchromatix_SKUAA_ST_gc0339_preview.so > /sdcard/chromatix_SKUAA_ST_gc0339_preview.h
/data/chromatix-test /system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_common.so > /sdcard/chromatix_SKUAB_ST_s5k4e1_common.h
/data/chromatix-test /system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_default_video.so > /sdcard/chromatix_SKUAB_ST_s5k4e1_default_video.h
/data/chromatix-test /system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_120fps.so > /sdcard/chromatix_SKUAB_ST_s5k4e1_hfr_120fps.h
/data/chromatix-test /system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_60fps.so > /sdcard/chromatix_SKUAB_ST_s5k4e1_hfr_60fps.h
/data/chromatix-test /system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_90fps.so > /sdcard/chromatix_SKUAB_ST_s5k4e1_hfr_90fps.h
/data/chromatix-test /system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_liveshot.so > /sdcard/chromatix_SKUAB_ST_s5k4e1_liveshot.h
/data/chromatix-test /system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_preview.so > /sdcard/chromatix_SKUAB_ST_s5k4e1_preview.h
/data/chromatix-test /system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_snapshot.so > /sdcard/chromatix_SKUAB_ST_s5k4e1_snapshot.h
/data/chromatix-test /system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_video_hd.so > /sdcard/chromatix_SKUAB_ST_s5k4e1_video_hd.h
/data/chromatix-test /system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_zsl.so > /sdcard/chromatix_SKUAB_ST_s5k4e1_zsl.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx132_common.so > /sdcard/chromatix_imx132_common.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx132_default_video.so > /sdcard/chromatix_imx132_default_video.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx132_liveshot.so > /sdcard/chromatix_imx132_liveshot.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx132_preview.so > /sdcard/chromatix_imx132_preview.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx132_snapshot.so > /sdcard/chromatix_imx132_snapshot.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx134_common.so > /sdcard/chromatix_imx134_common.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx134_default_video.so > /sdcard/chromatix_imx134_default_video.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx134_hfr_120.so > /sdcard/chromatix_imx134_hfr_120.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx134_hfr_60.so > /sdcard/chromatix_imx134_hfr_60.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx134_preview.so > /sdcard/chromatix_imx134_preview.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx134_snapshot.so > /sdcard/chromatix_imx134_snapshot.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx135_common.so > /sdcard/chromatix_imx135_common.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx135_default_video.so > /sdcard/chromatix_imx135_default_video.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx135_hfr_120.so > /sdcard/chromatix_imx135_hfr_120.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx135_hfr_60.so > /sdcard/chromatix_imx135_hfr_60.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx135_hfr_90.so > /sdcard/chromatix_imx135_hfr_90.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx135_preview.so > /sdcard/chromatix_imx135_preview.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx135_snapshot.so > /sdcard/chromatix_imx135_snapshot.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx135_video_hd.so > /sdcard/chromatix_imx135_video_hd.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx214_common.so > /sdcard/chromatix_imx214_common.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx214_default_video.so > /sdcard/chromatix_imx214_default_video.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx214_hfr_120.so > /sdcard/chromatix_imx214_hfr_120.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx214_preview.so > /sdcard/chromatix_imx214_preview.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx214_snapshot.so > /sdcard/chromatix_imx214_snapshot.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx214_snapshot_hdr.so > /sdcard/chromatix_imx214_snapshot_hdr.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx214_snapshot_w.so > /sdcard/chromatix_imx214_snapshot_w.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx214_video_hdr.so > /sdcard/chromatix_imx214_video_hdr.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx214_video_hdr_uhd.so > /sdcard/chromatix_imx214_video_hdr_uhd.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx214_video_uhd.so > /sdcard/chromatix_imx214_video_uhd.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx215_common.so > /sdcard/chromatix_imx215_common.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx215_default_video.so > /sdcard/chromatix_imx215_default_video.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx215_hfr_120.so > /sdcard/chromatix_imx215_hfr_120.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx215_preview.so > /sdcard/chromatix_imx215_preview.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx215_snapshot.so > /sdcard/chromatix_imx215_snapshot.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx215_snapshot_hdr.so > /sdcard/chromatix_imx215_snapshot_hdr.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx215_snapshot_w.so > /sdcard/chromatix_imx215_snapshot_w.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx215_video_hdr.so > /sdcard/chromatix_imx215_video_hdr.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx215_video_hdr_uhd.so > /sdcard/chromatix_imx215_video_hdr_uhd.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx215_video_uhd.so > /sdcard/chromatix_imx215_video_uhd.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx219_common.so > /sdcard/chromatix_imx219_common.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx219_preview.so > /sdcard/chromatix_imx219_preview.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx219_default_video.so > /sdcard/chromatix_imx219_default_video.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx219_snapshot.so > /sdcard/chromatix_imx219_snapshot.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx224_common.so > /sdcard/chromatix_imx224_common.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx224_default_video.so > /sdcard/chromatix_imx224_default_video.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx224_hfr_120.so > /sdcard/chromatix_imx224_hfr_120.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx224_preview.so > /sdcard/chromatix_imx224_preview.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx224_snapshot.so > /sdcard/chromatix_imx224_snapshot.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx224_snapshot_hdr.so > /sdcard/chromatix_imx224_snapshot_hdr.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx224_snapshot_w.so > /sdcard/chromatix_imx224_snapshot_w.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx224_video_hdr.so > /sdcard/chromatix_imx224_video_hdr.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx224_video_hdr_uhd.so > /sdcard/chromatix_imx224_video_hdr_uhd.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx224_video_uhd.so > /sdcard/chromatix_imx224_video_uhd.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx225_common.so > /sdcard/chromatix_imx225_common.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx225_default_video.so > /sdcard/chromatix_imx225_default_video.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx225_hfr_120.so > /sdcard/chromatix_imx225_hfr_120.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx225_preview.so > /sdcard/chromatix_imx225_preview.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx225_snapshot.so > /sdcard/chromatix_imx225_snapshot.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx225_snapshot_hdr.so > /sdcard/chromatix_imx225_snapshot_hdr.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx225_snapshot_w.so > /sdcard/chromatix_imx225_snapshot_w.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx225_video_hdr.so > /sdcard/chromatix_imx225_video_hdr.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx225_video_hdr_uhd.so > /sdcard/chromatix_imx225_video_hdr_uhd.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx225_video_uhd.so > /sdcard/chromatix_imx225_video_uhd.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx226_common.so > /sdcard/chromatix_imx226_common.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx226_default_video.so > /sdcard/chromatix_imx226_default_video.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx226_hfr_120.so > /sdcard/chromatix_imx226_hfr_120.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx226_preview.so > /sdcard/chromatix_imx226_preview.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx226_snapshot.so > /sdcard/chromatix_imx226_snapshot.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx226_snapshot_hdr.so > /sdcard/chromatix_imx226_snapshot_hdr.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx226_snapshot_w.so > /sdcard/chromatix_imx226_snapshot_w.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx226_video_hdr.so > /sdcard/chromatix_imx226_video_hdr.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx226_video_hdr_uhd.so > /sdcard/chromatix_imx226_video_hdr_uhd.h
/data/chromatix-test /system/vendor/lib/libchromatix_imx226_video_uhd.so > /sdcard/chromatix_imx226_video_uhd.h
/data/chromatix-test /system/vendor/lib/libchromatix_ov2720_common.so > /sdcard/chromatix_ov2720_common.h
/data/chromatix-test /system/vendor/lib/libchromatix_ov2720_default_video.so > /sdcard/chromatix_ov2720_default_video.h
/data/chromatix-test /system/vendor/lib/libchromatix_ov2720_hfr.so > /sdcard/chromatix_ov2720_hfr.h
/data/chromatix-test /system/vendor/lib/libchromatix_ov2720_liveshot.so > /sdcard/chromatix_ov2720_liveshot.h
/data/chromatix-test /system/vendor/lib/libchromatix_ov2720_preview.so > /sdcard/chromatix_ov2720_preview.h
/data/chromatix-test /system/vendor/lib/libchromatix_ov2720_zsl.so > /sdcard/chromatix_ov2720_zsl.h
/data/chromatix-test /system/vendor/lib/libchromatix_ov4688_common.so > /sdcard/chromatix_ov4688_common.h
/data/chromatix-test /system/vendor/lib/libchromatix_ov4688_default_video.so > /sdcard/chromatix_ov4688_default_video.h
/data/chromatix-test /system/vendor/lib/libchromatix_ov4688_hfr.so > /sdcard/chromatix_ov4688_hfr.h
/data/chromatix-test /system/vendor/lib/libchromatix_ov4688_liveshot.so > /sdcard/chromatix_ov4688_liveshot.h
/data/chromatix-test /system/vendor/lib/libchromatix_ov4688_preview.so > /sdcard/chromatix_ov4688_preview.h
/data/chromatix-test /system/vendor/lib/libchromatix_ov4688_zsl.so > /sdcard/chromatix_ov4688_zsl.h
/data/chromatix-test /system/vendor/lib/libchromatix_ov4689_common.so > /sdcard/chromatix_ov4689_common.h
/data/chromatix-test /system/vendor/lib/libchromatix_ov4689_default_video.so > /sdcard/chromatix_ov4689_default_video.h
/data/chromatix-test /system/vendor/lib/libchromatix_ov4689_hfr.so > /sdcard/chromatix_ov4689_hfr.h
/data/chromatix-test /system/vendor/lib/libchromatix_ov4689_liveshot.so > /sdcard/chromatix_ov4689_liveshot.h
/data/chromatix-test /system/vendor/lib/libchromatix_ov4689_preview.so > /sdcard/chromatix_ov4689_preview.h
/data/chromatix-test /system/vendor/lib/libchromatix_ov4689_zsl.so > /sdcard/chromatix_ov4689_zsl.h
/data/chromatix-test /system/vendor/lib/libchromatix_ov5648_oty5f03_common.so > /sdcard/chromatix_ov5648_oty5f03_common.h
/data/chromatix-test /system/vendor/lib/libchromatix_ov5648_oty5f03_default_video.so > /sdcard/chromatix_ov5648_oty5f03_default_video.h
/data/chromatix-test /system/vendor/lib/libchromatix_ov5648_oty5f03_preview.so > /sdcard/chromatix_ov5648_oty5f03_preview.h
/data/chromatix-test /system/vendor/lib/libchromatix_ov5648_oty5f03_snapshot.so > /sdcard/chromatix_ov5648_oty5f03_snapshot.h
/data/chromatix-test /system/vendor/lib/libchromatix_ov5648_oty5f03_zsl.so > /sdcard/chromatix_ov5648_oty5f03_zsl.h
/data/chromatix-test /system/vendor/lib/libchromatix_ov8825_common.so > /sdcard/chromatix_ov8825_common.h
/data/chromatix-test /system/vendor/lib/libchromatix_ov8825_default_video.so > /sdcard/chromatix_ov8825_default_video.h
/data/chromatix-test /system/vendor/lib/libchromatix_ov8825_hfr_120fps.so > /sdcard/chromatix_ov8825_hfr_120fps.h
/data/chromatix-test /system/vendor/lib/libchromatix_ov8825_hfr_60fps.so > /sdcard/chromatix_ov8825_hfr_60fps.h
/data/chromatix-test /system/vendor/lib/libchromatix_ov8825_hfr_90fps.so > /sdcard/chromatix_ov8825_hfr_90fps.h
/data/chromatix-test /system/vendor/lib/libchromatix_ov8825_liveshot.so > /sdcard/chromatix_ov8825_liveshot.h
/data/chromatix-test /system/vendor/lib/libchromatix_ov8825_liveshot_hd.so > /sdcard/chromatix_ov8825_liveshot_hd.h
/data/chromatix-test /system/vendor/lib/libchromatix_ov8825_preview.so > /sdcard/chromatix_ov8825_preview.h
/data/chromatix-test /system/vendor/lib/libchromatix_ov8825_preview_hd.so > /sdcard/chromatix_ov8825_preview_hd.h
/data/chromatix-test /system/vendor/lib/libchromatix_ov8825_snapshot.so > /sdcard/chromatix_ov8825_snapshot.h
/data/chromatix-test /system/vendor/lib/libchromatix_ov8825_snapshot_hd.so > /sdcard/chromatix_ov8825_snapshot_hd.h
/data/chromatix-test /system/vendor/lib/libchromatix_ov8825_video_hd.so > /sdcard/chromatix_ov8825_video_hd.h
/data/chromatix-test /system/vendor/lib/libchromatix_ov8825_zsl.so > /sdcard/chromatix_ov8825_zsl.h
/data/chromatix-test /system/vendor/lib/libchromatix_ov8865_q8v18a_common.so > /sdcard/chromatix_ov8865_q8v18a_common.h
/data/chromatix-test /system/vendor/lib/libchromatix_ov8865_q8v18a_default_video.so > /sdcard/chromatix_ov8865_q8v18a_default_video.h
/data/chromatix-test /system/vendor/lib/libchromatix_ov8865_q8v18a_hfr_120fps.so > /sdcard/chromatix_ov8865_q8v18a_hfr_120fps.h
/data/chromatix-test /system/vendor/lib/libchromatix_ov8865_q8v18a_hfr_60fps.so > /sdcard/chromatix_ov8865_q8v18a_hfr_60fps.h
/data/chromatix-test /system/vendor/lib/libchromatix_ov8865_q8v18a_hfr_90fps.so > /sdcard/chromatix_ov8865_q8v18a_hfr_90fps.h
/data/chromatix-test /system/vendor/lib/libchromatix_ov8865_q8v18a_liveshot.so > /sdcard/chromatix_ov8865_q8v18a_liveshot.h
/data/chromatix-test /system/vendor/lib/libchromatix_ov8865_q8v18a_preview.so > /sdcard/chromatix_ov8865_q8v18a_preview.h
/data/chromatix-test /system/vendor/lib/libchromatix_ov8865_q8v18a_snapshot.so > /sdcard/chromatix_ov8865_q8v18a_snapshot.h
/data/chromatix-test /system/vendor/lib/libchromatix_ov8865_q8v18a_video_hd.so > /sdcard/chromatix_ov8865_q8v18a_video_hd.h
/data/chromatix-test /system/vendor/lib/libchromatix_ov8865_q8v18a_zsl.so > /sdcard/chromatix_ov8865_q8v18a_zsl.h
/data/chromatix-test /system/vendor/lib/libchromatix_ov9724_common.so > /sdcard/chromatix_ov9724_common.h
/data/chromatix-test /system/vendor/lib/libchromatix_ov9724_default_video.so > /sdcard/chromatix_ov9724_default_video.h
/data/chromatix-test /system/vendor/lib/libchromatix_ov9724_liveshot.so > /sdcard/chromatix_ov9724_liveshot.h
/data/chromatix-test /system/vendor/lib/libchromatix_ov9724_preview.so > /sdcard/chromatix_ov9724_preview.h
/data/chromatix-test /system/vendor/lib/libchromatix_s5k3l1yx_common.so > /sdcard/chromatix_s5k3l1yx_common.h
/data/chromatix-test /system/vendor/lib/libchromatix_s5k3l1yx_default_video.so > /sdcard/chromatix_s5k3l1yx_default_video.h
/data/chromatix-test /system/vendor/lib/libchromatix_s5k3l1yx_hfr_120fps.so > /sdcard/chromatix_s5k3l1yx_hfr_120fps.h
/data/chromatix-test /system/vendor/lib/libchromatix_s5k3l1yx_hfr_60fps.so > /sdcard/chromatix_s5k3l1yx_hfr_60fps.h
/data/chromatix-test /system/vendor/lib/libchromatix_s5k3l1yx_hfr_90fps.so > /sdcard/chromatix_s5k3l1yx_hfr_90fps.h
/data/chromatix-test /system/vendor/lib/libchromatix_s5k3l1yx_liveshot.so > /sdcard/chromatix_s5k3l1yx_liveshot.h
/data/chromatix-test /system/vendor/lib/libchromatix_s5k3l1yx_preview.so > /sdcard/chromatix_s5k3l1yx_preview.h
/data/chromatix-test /system/vendor/lib/libchromatix_s5k3l1yx_snapshot.so > /sdcard/chromatix_s5k3l1yx_snapshot.h
/data/chromatix-test /system/vendor/lib/libchromatix_s5k3l1yx_video_hd.so > /sdcard/chromatix_s5k3l1yx_video_hd.h
/data/chromatix-test /system/vendor/lib/libchromatix_s5k3l1yx_zsl.so > /sdcard/chromatix_s5k3l1yx_zsl.h
/data/chromatix-test /system/vendor/lib/libchromatix_s5k3m2_common.so > /sdcard/chromatix_s5k3m2_common.h
/data/chromatix-test /system/vendor/lib/libchromatix_s5k3m2_default_video.so > /sdcard/chromatix_s5k3m2_default_video.h
/data/chromatix-test /system/vendor/lib/libchromatix_s5k3m2_hfr_120fps.so > /sdcard/chromatix_s5k3m2_hfr_120fps.h
/data/chromatix-test /system/vendor/lib/libchromatix_s5k3m2_preview.so > /sdcard/chromatix_s5k3m2_preview.h
/data/chromatix-test /system/vendor/lib/libchromatix_s5k3m2_snapshot.so > /sdcard/chromatix_s5k3m2_snapshot.h
/data/chromatix-test /system/vendor/lib/libchromatix_s5k3m2_snapshot_hdr.so > /sdcard/chromatix_s5k3m2_snapshot_hdr.h
/data/chromatix-test /system/vendor/lib/libchromatix_s5k3m2_snapshot_w.so > /sdcard/chromatix_s5k3m2_snapshot_w.h
/data/chromatix-test /system/vendor/lib/libchromatix_s5k3m2_video_hdr.so > /sdcard/chromatix_s5k3m2_video_hdr.h
/data/chromatix-test /system/vendor/lib/libchromatix_s5k3m2_video_hdr_uhd.so > /sdcard/chromatix_s5k3m2_video_hdr_uhd.h
/data/chromatix-test /system/vendor/lib/libchromatix_s5k3m2_video_uhd.so > /sdcard/chromatix_s5k3m2_video_uhd.h
/data/chromatix-test /system/vendor/lib/libchromatix_skuab_shinetech_gc0339_common.so > /sdcard/chromatix_skuab_shinetech_gc0339_common.h
/data/chromatix-test /system/vendor/lib/libchromatix_skuab_shinetech_gc0339_default_video.so > /sdcard/chromatix_skuab_shinetech_gc0339_default_video.h
/data/chromatix-test /system/vendor/lib/libchromatix_skuab_shinetech_gc0339_liveshot.so > /sdcard/chromatix_skuab_shinetech_gc0339_liveshot.h
/data/chromatix-test /system/vendor/lib/libchromatix_skuab_shinetech_gc0339_preview.so > /sdcard/chromatix_skuab_shinetech_gc0339_preview.h
/data/chromatix-test /system/vendor/lib/libchromatix_skuab_shinetech_gc0339_snapshot.so > /sdcard/chromatix_skuab_shinetech_gc0339_snapshot.h
/data/chromatix-test /system/vendor/lib/libchromatix_skuab_shinetech_gc0339_zsl.so > /sdcard/chromatix_skuab_shinetech_gc0339_zsl.h
/data/chromatix-test /system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_common.so > /sdcard/chromatix_skuf_ov12830_p12v01c_common.h
/data/chromatix-test /system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_default_video.so > /sdcard/chromatix_skuf_ov12830_p12v01c_default_video.h
/data/chromatix-test /system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_120fps.so > /sdcard/chromatix_skuf_ov12830_p12v01c_hfr_120fps.h
/data/chromatix-test /system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_60fps.so > /sdcard/chromatix_skuf_ov12830_p12v01c_hfr_60fps.h
/data/chromatix-test /system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_90fps.so > /sdcard/chromatix_skuf_ov12830_p12v01c_hfr_90fps.h
/data/chromatix-test /system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_preview.so > /sdcard/chromatix_skuf_ov12830_p12v01c_preview.h
/data/chromatix-test /system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_snapshot.so > /sdcard/chromatix_skuf_ov12830_p12v01c_snapshot.h
/data/chromatix-test /system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_video_hd.so > /sdcard/chromatix_skuf_ov12830_p12v01c_video_hd.h
/data/chromatix-test /system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_zsl.so > /sdcard/chromatix_skuf_ov12830_p12v01c_zsl.h
/data/chromatix-test /system/vendor/lib/libchromatix_skuf_ov5648_p5v23c_common.so > /sdcard/chromatix_skuf_ov5648_p5v23c_common.h
/data/chromatix-test /system/vendor/lib/libchromatix_skuf_ov5648_p5v23c_default_video.so > /sdcard/chromatix_skuf_ov5648_p5v23c_default_video.h
/data/chromatix-test /system/vendor/lib/libchromatix_skuf_ov5648_p5v23c_preview.so > /sdcard/chromatix_skuf_ov5648_p5v23c_preview.h
/data/chromatix-test /system/vendor/lib/libchromatix_skuf_ov5648_p5v23c_snapshot.so > /sdcard/chromatix_skuf_ov5648_p5v23c_snapshot.h
